<?php
/** @var \Adminaut\Form\Form $form */
$form = $this->form;
$form->setAttribute('action', $this->url('adminaut/users/add'));
$form->setAttribute('data-doubleClick', true);
$form->prepare();
?>
<section class="content-header">
    <h1>
        <?php echo $this->translate('Users') ?>
        <small><?php echo $this->translate('Add user') ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Users'), 'url' => $this->url('adminaut/users')],
            ['title' => _('Add user')],
        ],
    ]) ?>
</section>

<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="box">
        <?php echo $this->form()->openTag($form) ?>

        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->translate('Add user') ?></h3>
        </div>

        <div class="box-body">
            <?php echo $this->formCollection($form) ?>
        </div>

        <div class="box-footer clearfix">
            <button type="submit" name="submit" class="btn btn-primary" value="create">
                <?php echo $this->translate('Create') ?>
            </button>
            <button type="submit" name="submit" class="btn btn-default" value="create-and-continue">
                <?php echo $this->translate('Create and continue') ?>
            </button>
            <button type="submit" name="submit" class="btn btn-default" value="create-and-new">
                <?php echo $this->translate('Create and new') ?>
            </button>
            <a href="<?php echo $this->url('adminaut/users') ?>" class="btn btn-link">
                <?php echo $this->translate('Back to list') ?>
            </a>
        </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
</section>
