<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('adminaut/users/add'));
    $form->prepare();
?>
<section class="content-header">
    <h1>
        <?php echo $this->translate('Users:') ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard') ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="<?php echo $this->url('adminaut/users'); ?>">Users</a></li>
        <li class="active">Add</li>
    </ol>
</section>

<section class="content">
    <?php echo $this->form(null, null)->openTag($form); ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Add new user</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->partial('partial/flashMessanger.phtml', ['flashMessenger' => $this->flashMessenger()]); ?>

                    <?php echo $this->formCollection($form); ?>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <button type="submit" name="submit" class="btn btn-primary" value="">Create</button>
                    <button type="submit" name="submit" class="btn btn-default" value="">Create and continue</button>
                    <a href="<?php echo $this->url('adminaut/users'); ?>" class="btn btn-link"><?php echo $this->translate('Back to list'); ?></a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>