<?php
/** @var \Adminaut\Form\Form $form */
$form = $this->form;
$form->setAttribute('action', $this->url('adminaut/users/edit', ['id' => $this->user->getId()]));
$form->setAttribute('data-doubleClick', true);
$form->prepare();
?>
<section class="content-header">
    <h1>
        <?php echo $this->translate('Users', 'adminaut') ?>
        <small><?php echo $this->translate('Edit user', 'adminaut') ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Users'), 'url' => $this->url('adminaut/users')],
            ['title' => _('Edit user')],
        ],
    ]) ?>
</section>

<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="box">
        <?php echo $this->form()->openTag($form) ?>

        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->translate('Edit user', 'adminaut') ?></h3>
        </div>

        <div class="box-body">
            <?php echo $this->formCollection($form) ?>
        </div>

        <div class="box-footer clearfix">
            <button type="submit" name="submit" class="btn btn-primary" value="save">
                <?php echo $this->translate('Save', 'adminaut') ?>
            </button>
            <button type="submit" name="submit" class="btn btn-default" value="save-and-continue">
                <?php echo $this->translate('Save and continue', 'adminaut') ?>
            </button>
            <a href="<?php echo $this->url('adminaut/users') ?>" class="btn btn-link">
                <?php echo $this->translate('Back to list', 'adminaut') ?>
            </a>
            <a href="#" data-href="<?php echo $this->url('adminaut/users/delete', ['id' => $this->user->getId()]) ?>" class="btn btn-danger pull-right btn-modal-delete">
                <?php echo $this->translate('Delete', 'adminaut') ?>
            </a>
        </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
</section>

<?php echo $this->partial('adminaut/partial/deleteModal') ?>
