<?php
$form = $this->form;
$form->setAttribute('action', $this->url('adminaut/users/edit', ['id' => $this->user->getId()]));
$form->prepare();
?>
<section class="content-header">
    <h1>
        <?php echo $this->translate('Users:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard') ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/users'); ?>"><?php echo $this->translate("Users"); ?></a></li>
        <li class="active"><?php echo $this->translate("Update"); ?></li>
    </ol>
</section>

<section class="content">
    <?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <div class="nav-tabs-custom">
                <?php if(sizeof($this->tabs) > 1) { ?>
                    <?php echo $this->partial('partial/tabs.phtml', ['route' => 'adminaut/users/edit', 'url_params' => $this->url_params, 'tabs' => $this->tabs]); ?>
                <?php } else { ?>
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate("Update"); ?></h3>
                    </div>
                <?php } ?>
                <div class="tab-content">
                    <?php echo $this->partial('partial/messages'); ?>

                    <?php echo $this->formCollection($form); ?>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <button type="submit" name="submit" value="save" class="btn btn-primary"><?php echo $this->translate('Save'); ?></button>
                    <button type="submit" name="submit" value="save-and-continue" class="btn btn-default"><?php echo $this->translate('Save and continue'); ?></button>
                    <a href="<?php echo $this->url('adminaut/users'); ?>" class="btn btn-link"><?php echo $this->translate('Back to list'); ?></a>
                    <a href="<?php echo $this->url('adminaut/users/delete', ['id' => $this->user->getId()]); ?>" class="btn btn-danger pull-right"><?php echo $this->translate('Delete'); ?></a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>
