<section class="content-header">
    <h1>
        <?php echo $this->translate('Users') ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut-dashboard') ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active">Users</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Users</h3>

                    <div class="box-tools pull-right">
                        <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                            <a href="<?php echo $this->url('adminaut-users/add'); ?>" class="btn btn-box-tool"><i class="fa fa-user-plus"></i></a>
                        <?php } ?>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->partial('partial/flashMessanger.phtml', ['flashMessenger' => $this->flashMessenger()]); ?>

                    <table id="usersTable" class="table table-striped table-bordered table-hover dataTables">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><?php echo $this->translate('Name'); ?></th>
                                <th><?php echo $this->translate('Email'); ?></th>
                                <th><?php echo $this->translate('Role'); ?></th>
                                <th><?php echo $this->translate('Status'); ?></th>
                                <th><?php echo $this->translate('Actions'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->list as $entity) { ?>
                                <?php /* @var $entity \Adminaut\Entity\UserEntity */ ?>
                                <tr>
                                    <td><?php echo $entity->getId(); ?></td>
                                    <td><?php echo $entity->getName(); ?></td>
                                    <td><?php echo $entity->getEmail(); ?></td>
                                    <td><?php echo $entity->getRole(); ?></td>
                                    <td>
                                        <?php if ($entity->isActive()) { ?>
                                            <span class="label label-success"><?php echo $this->translate('Active'); ?></span>
                                        <?php } else { ?>
                                            <span class="label label-danger"><?php echo $this->translate('Inactive'); ?></span>
                                        <?php } ?>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
                                            <a href="<?php echo $this->url('adminaut-users/show', ['id' => $entity->getId()]); ?>" type="button" class="btn btn-success"><i class="fa fa-eye"></i></a>
                                            <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                                                <a href="<?php echo $this->url('adminaut-users/update', ['id' => $entity->getId()]); ?>" type="button" class="btn btn-info"><i class="fa fa-pencil"></i></a>
                                            <?php } if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::FULL)) { ?>
                                                <a href="<?php echo $this->url('adminaut-users/delete', ['id' => $entity->getId()]); ?>" type="button" class="btn btn-danger btn-modal-delete"><i class="fa fa-user-times"></i></a>
                                            <?php } ?>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <script>
                        (function($){
                            $('#usersTable').DataTable({
                                "paging": true,
                                "lengthChange": false,
                                "searching": true,
                                "ordering": true,
                                "info": true,
                                "autoWidth": false
                            });
                        })(jQuery);
                    </script>
                </div>
                <!-- /.box-body -->

                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                        <a href="<?php echo $this->url('adminaut-users/add'); ?>" class="btn btn-sm btn-primary btn-flat pull-left"><i class="fa fa-user-plus"></i> <?php echo $this->translate('Add user'); ?></a>
                    <?php } ?>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<?php echo $this->partial('partial/deleteModal.phtml'); ?>