<section class="content-header">
    <h1>
        <?php echo $this->translate('Users') ?>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Users')],
        ],
    ]) ?>
</section>

<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="box">

        <div class="box-header with-border">
            <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                <a href="<?php echo $this->url('adminaut/users/add'); ?>" class="btn btn-primary">
                    <?php echo $this->translate('Add user') ?>
                </a>
            <?php } ?>
        </div>

        <div class="box-body">
            <table id="usersTable" class="table table-striped table-bordered table-hover dataTables">
                <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Name') ?></th>
                    <th><?php echo $this->translate('Email') ?></th>
                    <th><?php echo $this->translate('Role') ?></th>
                    <th><?php echo $this->translate('Status') ?></th>
                    <th><?php echo $this->translate('Actions') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->list as $entity) { ?>
                    <?php /* @var $entity \Adminaut\Entity\UserEntityInterface */ ?>
                    <tr>
                        <td><?php echo $entity->getId() ?></td>
                        <td><?php echo $this->escapeHtml($entity->getName()) ?></td>
                        <td><?php echo $this->escapeHtml($entity->getEmail()) ?></td>
                        <td><?php echo $this->escapeHtml($entity->getRole()) ?></td>
                        <td>
                            <?php if ($entity->isActive()) { ?>
                                <span class="label label-success"><?php echo $this->translate('Active') ?></span>
                            <?php } else { ?>
                                <span class="label label-danger"><?php echo $this->translate('Inactive') ?></span>
                            <?php } ?>
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
                                <a href="<?php echo $this->url('adminaut/users/view', ['id' => $entity->getId()]) ?>" type="button" class="btn btn-success">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                                    <a href="<?php echo $this->url('adminaut/users/edit', ['id' => $entity->getId()]) ?>" type="button" class="btn btn-info">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                <?php }
                                if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::FULL)) { ?>
                                    <a href="#" data-href="<?php echo $this->url('adminaut/users/delete', ['id' => $entity->getId()]) ?>" type="button"
                                       class="btn btn-danger btn-modal-delete">
                                        <i class="fa fa-user-times"></i>
                                    </a>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>

        <div class="box-footer clearfix">
            <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                <a href="<?php echo $this->url('adminaut/users/add') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Add user') ?>
                </a>
            <?php } ?>
        </div>

    </div>
</section>

<script>
    (function ($) {
        $('#usersTable').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    })(jQuery);
</script>

<?php echo $this->partial('partial/deleteModal.phtml') ?>