<section class="content-header">
    <h1>
        <?php echo $this->translate('Users:') ?>
        <small><?php echo $this->user->getName() ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut-dashboard') ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="<?php echo $this->url('adminaut-users/list'); ?>">Users</a></li>
        <li class="active">Detail</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Detail</h3>

                    <div class="box-tools pull-right">
                        <?php if ($this->isAllowed('users', \Adminaut\Service\AccessControlService::WRITE)) { ?>
                            <a href="<?php echo $this->url('adminaut-users/update', ['id' => $this->user->getId()]); ?>" class="btn btn-box-tool"><i class="fa fa-pencil"></i></a>
                        <?php } ?>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h4><?php echo $this->translate('Name'); ?></h4>
                    <p>
                        <?php echo $this->user->getName(); ?>
                    </p>
                    <hr />

                    <h4><?php echo $this->translate('Email'); ?></h4>
                    <p>
                        <?php echo $this->user->getEmail(); ?>
                    </p>
                    <hr />

                    <h4><?php echo $this->translate('Active'); ?></h4>
                    <p>
                        <?php if ($this->user->isActive()) { ?>
                            <span class="label label-success"><?php echo $this->translate('Active'); ?></span>
                        <?php } else { ?>
                            <span class="label label-danger"><?php echo $this->translate('Inactive'); ?></span>
                        <?php } ?>
                    </p>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <a href="<?php echo $this->url('adminaut-users'); ?>" class="btn btn-sm btn-default btn-flat pull-left"><i class="fa fa-chevron-left"></i> <?php echo $this->translate('Back'); ?></a>
                    <?php if ($this->isAllowed('users', 2)) { ?>
                        <a href="<?php echo $this->url('adminaut-users/update', ['id' => $this->user->getId()]); ?>" class="btn btn-sm btn-primary btn-flat pull-left"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
                    <?php } ?>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
</section>