<section class="content-header">
    <h1>
        <?php echo $this->translate('Users:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard'); ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/users'); ?>"><?php echo $this->translate("Users"); ?></a></li>
        <li class="active"><?php echo $this->translate("Detail"); ?></li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate("Detail"); ?></h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h4><?php echo $this->translate('Name'); ?></h4>
                    <p>
                        <?php echo $this->escapeHtml($this->user->getName()); ?>
                    </p>
                    <hr/>

                    <h4><?php echo $this->translate('Email'); ?></h4>
                    <p>
                        <?php echo $this->escapeHtml($this->user->getEmail()); ?>
                    </p>
                    <hr/>

                    <h4><?php echo $this->translate('Active'); ?></h4>
                    <p>
                        <?php if ($this->user->isActive()) { ?>
                            <span class="label label-success"><?php echo $this->translate('Active'); ?></span>
                        <?php } else { ?>
                            <span class="label label-danger"><?php echo $this->translate('Inactive'); ?></span>
                        <?php } ?>
                    </p>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed('users', 2)) { ?>
                        <a href="<?php echo $this->url('adminaut/users/edit', ['id' => $this->user->getId()]); ?>" class="btn btn-primary">
                            <?php echo $this->translate('Edit'); ?>
                        </a>
                    <?php } ?>
                    <a href="<?php echo $this->url('adminaut/users'); ?>" class="btn btn-link">
                        <?php echo $this->translate('Back to list'); ?>
                    </a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
</section>
