<section class="content-header">
    <h1>
        <?php echo $this->translate('Users', 'adminaut') ?>
        <small><?php echo $this->escapeHtml($this->user->getName()) ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Users'), 'url' => $this->url('adminaut/users')],
            ['title' => _('Detail')],
        ],
    ]) ?>
</section>

<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $this->translate('Detail', 'adminaut') ?></h3>
        </div>
        <div class="box-body">
            <h4><?php echo $this->translate('Name', 'adminaut') ?></h4>
            <p>
                <?php echo $this->escapeHtml($this->user->getName()) ?>
            </p>
            <hr/>

            <h4><?php echo $this->translate('Email', 'adminaut') ?></h4>
            <p>
                <?php echo $this->escapeHtml($this->user->getEmail()) ?>
            </p>
            <hr/>

            <h4><?php echo $this->translate('Active', 'adminaut') ?></h4>
            <p>
                <?php if ($this->user->isActive()) { ?>
                    <span class="label label-success"><?php echo $this->translate('Active', 'adminaut') ?></span>
                <?php } else { ?>
                    <span class="label label-danger"><?php echo $this->translate('Inactive', 'adminaut') ?></span>
                <?php } ?>
            </p>
        </div>
        <div class="box-footer">
            <?php if ($this->isAllowed('users', 2)) { ?>
                <a href="<?php echo $this->url('adminaut/users/edit', ['id' => $this->user->getId()]) ?>" class="btn btn-primary">
                    <?php echo $this->translate('Edit', 'adminaut') ?>
                </a>
            <?php } ?>
            <a href="<?php echo $this->url('adminaut/users') ?>" class="btn btn-link">
                <?php echo $this->translate('Back to list', 'adminaut') ?>
            </a>
        </div>
    </div>
</section>
