<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard'); ?>"><?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/profile'); ?>"><?php echo $this->translate("Profile"); ?></a></li>
        <li class="active"><?php echo $this->translate("Access tokens"); ?></li>
    </ol>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li><a href="<?php echo $this->url('adminaut/profile'); ?>">Overview</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/change-password'); ?>">Change password</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/logins'); ?>">Logins</a></li>
            <li class="active"><a href="<?php echo $this->url('adminaut/profile/access-tokens'); ?>">Access tokens</a></li>
        </ul>
        <div class="tab-content">

        </div>
    </div>
</section>
