<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile', 'adminaut') ?>
        <small><?php echo $this->escapeHtml($this->user->getName()) ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Profile'), 'url' => $this->url('adminaut/profile')],
            ['title' => _('Access tokens')],
        ],
    ]) ?>
</section>
<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li>
                <a href="<?php echo $this->url('adminaut/profile') ?>">
                    <?php echo $this->translate('Overview', 'adminaut') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/settings') ?>">
                    <?php echo $this->translate('Settings', 'adminaut') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/change-password') ?>">
                    <?php echo $this->translate('Change password', 'adminaut') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/logins') ?>">
                    <?php echo $this->translate('Logins', 'adminaut') ?>
                </a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('adminaut/profile/access-tokens') ?>">
                    <?php echo $this->translate('Access tokens', 'adminaut') ?>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <table class="table table-striped table-bordered table-hover" id="dataTable">
                <thead>
                <tr>
                    <th style="width: 16px">#</th>
                    <th><?php echo $this->translate('Hash', 'adminaut') ?></th>
                    <th><?php echo $this->translate('Created', 'adminaut') ?></th>
                    <th style="width: 40px"><?php echo $this->translate('Action', 'adminaut') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Adminaut\Entity\UserAccessTokenEntity $accessToken */ ?>
                <?php foreach ($this->accessTokens as $accessToken) { ?>
                    <tr>
                        <td><?php echo $accessToken->getId() ?></td>
                        <td><?php echo $accessToken->getHash() ?></td>
                        <td><?php echo $accessToken->getInserted()->format('Y-m-d H:i') ?></td>
                        <td>
                            <a class="btn btn-xs btn-danger" href="<?php echo $this->url('adminaut/profile/access-tokens/delete', ['id' => $accessToken->getId()]) ?>">
                                <?php echo $this->translate('Delete', 'adminaut') ?>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <div class="text-center">
                <a class="btn btn-danger" href="<?php echo $this->url('adminaut/profile/access-tokens/delete-all') ?>">
                    <?php echo $this->translate('Delete all', 'adminaut') ?>
                </a>
            </div>
        </div>
    </div>
</section>
<script>
    (function ($) {
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "order": [[0, "desc"]]
            });
        });
    })(jQuery);
</script>
