<?php $this->form->prepare(); ?>
<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard'); ?>"><?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/profile'); ?>"><?php echo $this->translate("Profile"); ?></a></li>
        <li class="active"><?php echo $this->translate("Change password"); ?></li>
    </ol>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li><a href="<?php echo $this->url('adminaut/profile'); ?>">Overview</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/settings'); ?>">Settings</a></li>
            <li class="active"><a href="<?php echo $this->url('adminaut/profile/change-password'); ?>">Change password</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/logins'); ?>">Logins</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/access-tokens'); ?>">Access tokens</a></li>
        </ul>
        <div class="tab-content">
            <div class="row">
                <div class="col-md-8">
                    <?php echo $this->partial('partial/messages'); ?>
                    <?php echo $this->form()->openTag($this->form) ?>
                    <?php echo $this->formCollection($this->form) ?>
                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">
                            <button class="btn btn-primary"><?php echo $this->translate('Change'); ?></button>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</section>
