<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard'); ?>"><?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/profile'); ?>"><?php echo $this->translate("Profile"); ?></a></li>
        <li class="active"><?php echo $this->translate("Overview"); ?></li>
    </ol>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="<?php echo $this->url('adminaut/profile'); ?>">Overview</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/change-password'); ?>">Change password</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/logins'); ?>">Logins</a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/access-tokens'); ?>">Access tokens</a></li>
        </ul>
        <div class="tab-content">
            <h4><?php echo $this->translate('Name'); ?></h4>
            <p>
                <?php echo $this->escapeHtml($this->user->getName()); ?>
            </p>
            <hr/>

            <h4><?php echo $this->translate('Email'); ?></h4>
            <p>
                <?php echo $this->escapeHtml($this->user->getEmail()); ?>
            </p>
            <hr/>

            <h4><?php echo $this->translate('Active'); ?></h4>
            <p>
                <?php if ($this->user->isActive()) { ?>
                    <span class="label label-success"><?php echo $this->translate('Active'); ?></span>
                <?php } else { ?>
                    <span class="label label-danger"><?php echo $this->translate('Inactive'); ?></span>
                <?php } ?>
            </p>
        </div>
    </div>
</section>
