<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile') ?>
        <small><?php echo $this->escapeHtml($this->user->getName()) ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => _('Profile'), 'url' => $this->url('adminaut/profile')],
            ['title' => _('Logins')],
        ],
    ]) ?>
</section>
<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li>
                <a href="<?php echo $this->url('adminaut/profile') ?>">
                    <?php echo $this->translate('Overview') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/settings') ?>">
                    <?php echo $this->translate('Settings') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/change-password') ?>">
                    <?php echo $this->translate('Change password') ?>
                </a>
            </li>
            <li class="active">
                <a href="<?php echo $this->url('adminaut/profile/logins') ?>">
                    <?php echo $this->translate('Logins') ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('adminaut/profile/access-tokens') ?>">
                    <?php echo $this->translate('Access tokens') ?>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <table class="table table-striped table-bordered table-hover" id="dataTable">
                <thead>
                <tr>
                    <th style="width: 16px">#</th>
                    <th><?php echo $this->translate('Type') ?></th>
                    <th><?php echo $this->translate('Created') ?></th>
                    <th><?php echo $this->translate('IP Address') ?></th>
                    <th><?php echo $this->translate('User Agent') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Adminaut\Entity\UserLoginEntity $login */ ?>
                <?php foreach ($this->logins as $login) { ?>
                    <tr>
                        <td><?php echo $login->getId() ?></td>
                        <td>
                            <?php if (\Adminaut\Entity\UserLoginEntity::TYPE_FAILED === $login->getType()) { ?>
                                <span class="label label-danger"><?php echo $this->translate('Failed') ?></span>
                            <?php } else { ?>
                                <span class="label label-success"><?php echo $this->translate('Success') ?></span>
                            <?php } ?>
                        </td>
                        <td><?php echo $login->getInserted()->format('Y-m-d H:i') ?></td>
                        <td><?php echo $login->getIpAddress() ?></td>
                        <td><?php echo $login->getUserAgent() ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</section>
<script>
    (function ($) {
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "order": [[0, "desc"]]
            });
        });
    })(jQuery);
</script>
