<section class="content-header">
    <h1>
        <?php echo $this->translate('Profile:'); ?>
        <small><?php echo $this->escapeHtml($this->user->getName()); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard'); ?>"><?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/profile'); ?>"><?php echo $this->translate("Profile"); ?></a></li>
        <li class="active"><?php echo $this->translate("Logins"); ?></li>
    </ol>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li><a href="<?php echo $this->url('adminaut/profile'); ?>"><?php echo $this->translate('Overview') ?></a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/settings'); ?>"><?php echo $this->translate('Settings') ?></a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/change-password'); ?>"><?php echo $this->translate('Change password') ?></a></li>
            <li class="active"><a href="<?php echo $this->url('adminaut/profile/logins'); ?>"><?php echo $this->translate('Logins') ?></a></li>
            <li><a href="<?php echo $this->url('adminaut/profile/access-tokens'); ?>"><?php echo $this->translate('Access tokens') ?></a></li>
        </ul>
        <div class="tab-content">
            <table class="table table-striped table-bordered table-hover" id="dataTable">
                <thead>
                <tr>
                    <th style="width: 16px">#</th>
                    <th>Type</th>
                    <th>Created</th>
                    <th>IP Address</th>
                    <th>User Agent</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Adminaut\Entity\UserLoginEntity $login */ ?>
                <?php foreach ($this->logins as $login) { ?>
                    <tr>
                        <td><?php echo $login->getId(); ?>.</td>
                        <td>
                            <?php if (\Adminaut\Entity\UserLoginEntity::TYPE_FAILED === $login->getType()) { ?>
                                <span class="label label-danger">Failed</span>
                            <?php } else { ?>
                                <span class="label label-success">Successful</span>
                            <?php } ?>
                        </td>
                        <td><?php echo $login->getInserted()->format('Y-m-d H:i'); ?></td>
                        <td><?php echo $login->getIpAddress(); ?></td>
                        <td><?php echo $login->getUserAgent(); ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</section>

<script>
    (function ($) {
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "order": [[0, "desc"]]
            });
        });
    })(jQuery);
</script>
