<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Adminaut\Module' => __DIR__ . '/Module.php',
    'Adminaut\Controller\IndexController' => __DIR__ . '/src/Adminaut/Controller/IndexController.php',
];