<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->translate('Role'); ?>: <?php echo $this->role->getName(); ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">

            <div class="panel-heading"><i class="fa fa-lock fa-fw"></i> <?php echo $this->translate('Permission'); ?></div>
            <table class="table">
                <tbody>
                <tr>
                    <td width="100">Dashboard</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="toolbar" aria-label="Dashboard">
                            <button type="button" class="btn btn-active-info active"><?php echo $this->translate('Read'); ?></button>
                        </div>
                    </td>
                </tr>
                <?php foreach ($this->modules as $index => $module) { ?>
                    <tr>
                        <td><?php echo $module['module_name']; ?></td>
                        <td>
                            <div class="btn-group btn-group-sm" role="toolbar" aria-label="<?php echo $module['module_name']; ?>">
                                <?php if ($this->role->getName() == 'admin') { ?>
                                    <button type="button" class="btn btn-active-info active"><?php echo $this->translate('Read'); ?></button>
                                    <button type="button" class="btn btn-active-success active"><?php echo $this->translate('Write'); ?></button>
                                <?php } else if (isset($this->rolePermissions[$module['module_name']])) { ?>
                                    <?php $permission = $this->rolePermissions[$module['module_name']]; ?>
                                    <?php if ($permission == 1) { ?>
                                        <button type="button" class="btn btn-active-info active"><?php echo $this->translate('Read'); ?></button>
                                    <?php } elseif ($permission == 2) { ?>
                                        <button type="button" class="btn btn-active-info active"><?php echo $this->translate('Read'); ?></button>
                                        <button type="button" class="btn btn-active-success active"><?php echo $this->translate('Write'); ?></button>
                                    <?php } else { ?>
                                        <button type="button" class="btn btn-active-danger active"><?php echo $this->translate('None'); ?></button>
                                    <?php } ?>
                                <?php } else { ?>
                                    <button type="button" class="btn btn-active-danger active"><?php echo $this->translate('None'); ?></button>
                                <?php } ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if ($this->isAllowed('users', 1)) { ?>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-users fa-fw"></i> <?php echo $this->translate('Users assigned to role'); ?>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        <?php foreach ($this->role->getUsers() as $key => $user) { ?>
                            <?php /* @var $user MfccAdminModule\Entity\User */ ?>
                            <a href="<?php echo $this->url('adminaut/users/show', ['id' => $user->getId()]); ?>" class="list-group-item">
                                <i class="fa fa-user fa-fw"></i> <?php echo $user->getName(); ?>
                            </a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<div class="row">
    <div class="col-md-12">
        <a href="<?php echo $this->url('adminaut/acl'); ?>" type="button" class="btn btn-default"><i class="fa fa-chevron-left"></i> <?php echo $this->translate('Back'); ?></a>
        <?php if ($this->role->getId() != 1) { ?>
            <?php if ($this->isAllowed('roles', 2)) { ?>
                <a href="<?php echo $this->url('adminaut/acl/update-role', ['roleId' => $this->role->getId()]); ?>" type="button" class="btn btn-primary"><i class="fa fa-pencil"></i> <?php echo $this->translate('Edit'); ?></a>
            <?php } ?>
        <?php } ?>
    </div>
</div>