<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->translate('Update role'); ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">

        <?php echo $this->partial('partial/messages'); ?>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('adminaut/acl/update-role', ['roleId' => $this->role->getId()]));
        $form->prepare();

        echo $this->form(null, null)->openTag($form); ?>
        <?php echo $this->formRow($form->get('name')); ?>
        <?php if( $form->formMode === "update" ) { ?>
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate('Permission'); ?></div>
            <table class="table">
                <tbody>
                <?php $ignoredKeys = ['submit', 'name']; ?>
                <?php foreach ($form->getElements() as $key => $module) { ?>
                    <?php if(!in_array($key, $ignoredKeys)) { ?>
                        <tr>
                            <td><?php echo $module->getLabel(); ?></td>
                            <td>
                                <div class="btn-group btn-group-sm" data-toggle="buttons">
                                    <label class="btn btn-default btn-active-danger <?php echo ($module->getValue() == 0) ? 'active':'' ?>">
                                        <input type="radio" name="<?php echo $key ?>" id="<?php echo $key ?>-0" value="0" autocomplete="off" <?php echo ($module->getValue() == 0) ? 'checked':'' ?>> None
                                    </label>
                                    <label class="btn btn-default btn-active-info <?php echo ($module->getValue() == 1) ? 'active':'' ?>">
                                        <input type="radio" name="<?php echo $key ?>" id="<?php echo $key ?>-1" value="1" autocomplete="off" <?php echo ($module->getValue() == 1) ? 'checked':'' ?>> Read
                                    </label>
                                    <label class="btn btn-default btn-active-success <?php echo ($module->getValue() == 2) ? 'active':'' ?>">
                                        <input type="radio" name="<?php echo $key ?>" id="<?php echo $key ?>-2" value="2" autocomplete="off" <?php echo ($module->getValue() == 2) ? 'checked':'' ?>> Read & Write
                                    </label>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <?php } ?>
        <div class="form-group ">
            <a href="<?php echo $this->url('adminaut/acl'); ?>" type="button" class="btn btn-default"><i class="fa fa-chevron-left"></i> <?php echo $this->translate('Back'); ?></a>
            <button type="submit" name="submit" class="btn btn-primary" value="Save"><i class="fa fa-send fa"></i> Submit</button>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>