<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Confirm delete'); ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->translate('Are you sure?'); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('No'); ?></button>
                <a href="#" type="button" id="confirm" class="btn btn-danger"><?php echo $this->translate('Yes, delete it'); ?></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).on('click', '.btn-modal-delete', function(e){
        var deleteModal = $('#deleteModal');
        deleteModal.modal();
        deleteModal.find('#confirm').attr('href', $(this).data('href'));
        e.preventDefault();
    });
</script>