<?php if ($this->flashMessenger->hasSuccessMessages()) { ?>
    <?php foreach ($this->flashMessenger->getSuccessMessages() as $msg) { ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $msg; ?>
        </div>
    <?php } ?>
<?php } ?>

<?php if ($this->flashMessenger->hasInfoMessages()) { ?>
    <?php foreach ($this->flashMessenger->getInfoMessages() as $msg) { ?>
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $msg; ?>
        </div>
    <?php } ?>
<?php } ?>

<?php if ($this->flashMessenger->hasErrorMessages()) { ?>
    <?php foreach ($this->flashMessenger->getErrorMessages() as $msg) { ?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $msg; ?>
        </div>
    <?php } ?>
<?php } ?>
