<ul class="nav nav-tabs" role="tablist">
    <?php foreach($this->tabs as $tabName => $tab) { ?>
        <li role="presentation"<?php if(isset($tab['active']) && $tab['active']) { ?> class="active"<?php } ?>>
            <?php if($tabName == 'main') { ?>
                <a href="<?php echo $this->url($this->route, $this->url_params) ?>" aria-controls="<?php echo $tabName ?>" role="tab"><?php echo $tab['label'] ?></a>
            <?php } else { ?>
                <a href="<?php echo $this->url($this->route . '/tab', array_merge($this->url_params, ['tab' => $tabName])) ?>" aria-controls="<?php echo $tabName ?>" role="tab"><?php echo $tab['label'] ?></a>
            <?php } ?>
        </li>
    <?php } ?>
    <?php if(isset($this->actions)) {
        $this->actions = array_reverse($this->actions);
        foreach ($this->actions as $action) { ?>
            <li class="pull-right">
                <a href="<?php echo $action['url'] ?>" class="text-muted"><i class="<?php echo $action['icon'] ?>"></i></a>
            </li>
        <?php }
    } ?>
</ul>