<?php
    /** @var \Adminaut\Entity\UserEntityInterface $user */

    $title = sprintf($this->translate('Password recovery - %s', 'adminaut'), $this->system_name)
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $title ?></title>
</head>
<body>

    <h1><?php echo $title ?></h1>
    <p><?php echo sprintf($this->translate('Someone requested a new password for %s.', 'adminaut'), $this->email) ?></p>
    <p><?php echo sprintf($this->translate('For reset your password <a href="%s">click here</a>.', 'adminaut'), $this->url('adminaut/auth/password-recovery', ['email' => $email, 'key' => $recoveryKey], ['force_canonical' => true])) ?></p>
    <br />
    <p><?php echo sprintf($this->translate('Link will expire at <strong>%s</strong>', 'adminaut'), (new \DateTime('+15 minutes'))->format('j.n.Y H:i')) ?></p>
</body>
</html>