<?php
    $form = $this->form;
//    $form->setAttribute('action', $this->url('adminaut-module/action', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $this->entity->getId(), 'mode' => 'update']));
    $form->prepare();
?>

<section class="content-header">
    <h1>
        <?php echo $this->moduleOption->getModuleName() ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut-dashboard') ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="<?php echo $this->url('adminaut-module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>"><?php echo $this->moduleOption->getModuleName() ?></a></li>
        <li class="active"><?php echo $this->moduleOption->getLabels()['update_entity'] ?></li>
    </ol>
</section>

<section class="content">
    <?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-xs-12">
            <div class="nav-tabs-custom">
                <?php if(sizeof($this->tabs) > 1) { ?>
                    <?php echo $this->partial('partial/tabs.phtml', ['url_params' => $this->url_params, 'tabs' => $this->tabs]); ?>
                <?php } else { ?>
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->moduleOption->getLabels()['update_entity'] ?></h3>
                    </div>
                <?php } ?>
                <div class="tab-content">
                    <?php echo $this->partial('partial/flashMessanger.phtml', ['flashMessenger' => $this->flashMessenger()]); ?>

                    <?php echo $this->formCollection($form); ?>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <button type="submit" name="submit" class="btn btn-primary">Save</button>
                    <button type="submit" name="submit" class="btn btn-default">Save and continue</button>
                    <a href="<?php echo $this->url('adminaut-module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>" class="btn btn-link"><?php echo $this->translate('Back to list'); ?></a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</section>