<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($this->moduleOption->getModuleName()) ?>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => $this->moduleOption->getModuleName()],
        ],
    ]) ?>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'add']); ?>"
                           class="btn btn-primary pull-left"><i class="fa fa-plus"></i> <?php echo $this->translate($this->moduleOption->getLabels()['add_record'], 'adminaut') ?></a>
                    <?php } ?>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->partial('adminaut/partial/messages') ?>

                    <table id="moduleEntityTable" class="table table-striped table-bordered table-hover dataTables">
                        <thead>
                        <tr>
                            <th>#</th>
                            <?php foreach ($this->listedElements as $listedElement) { ?>
                                <th><?php echo $listedElement->getOption('label') ?></th>
                            <?php } ?>
                            <th><?php echo $this->translate('Actions', 'adminaut'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->list as $entity) { ?>
                            <?php /* @var $entity Adminaut\Entity\Base */ ?>
                            <tr rel="<?php echo $entity->getId(); ?>">
                                <td>
                                    <?php if (!$this->hasPrimary) { ?>
                                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'view', 'entity_id' => $entity->getId()]); ?>"
                                           class="primary"><?php echo $entity->getId(); ?></a>
                                    <?php } else { ?>
                                        <?php echo $entity->getId(); ?>
                                    <?php } ?>
                                </td>
                                <?php foreach ($this->listedElements as $listedElement) { ?>
                                    <td>
                                        <?php if ($listedElement->isPrimary()) { // TODO[petrm] check if method exists ?>
                                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'view', 'entity_id' => $entity->getId()]); ?>"
                                           class="primary">
                                            <?php } ?>
                                            <?php $listedElement->setValue($entity->{$listedElement->getName()}) ?>
                                            <?php if (method_exists($listedElement, 'getListedValue')) { ?>
                                                <?php echo($listedElement->isPrimary() && empty($listedElement->getListedValue()) ? 'undefined' : $listedElement->getListedValue()); ?>
                                            <?php } else { ?>
                                                <?php echo $listedElement->getValue(); ?>
                                            <?php } ?>
                                            <?php if ($listedElement->isPrimary()) { ?>
                                        </a>
                                    <?php } ?>
                                    </td>
                                <?php } ?>
                                <td class="action-column">
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
                                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'view', 'entity_id' => $entity->getId()]); ?>"
                                           class="btn btn-success view"
                                           data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('View', 'adminaut') ?>"
                                           data-original-title="<?php echo $this->translate('View', 'adminaut') ?>"><i class="fa fa-eye"></i></a>
                                        <?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) { ?>
                                            <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'edit', 'entity_id' => $entity->getId()]); ?>"
                                               class="btn btn-primary edit"
                                               data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Edit', 'adminaut') ?>"
                                               data-original-title="<?php echo $this->translate('Edit', 'adminaut') ?>"><i class="fa fa-pencil"></i></a>
                                            <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $entity->getId(), 'mode' => 'add']); ?>"
                                               class="btn btn-sm btn-default clone" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Copy', 'adminaut') ?>"
                                               data-original-title="<?php echo $this->translate('Copy', 'adminaut') ?>"><i class="fa fa-clone"></i></a>
                                        <?php }
                                        if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::FULL)) { ?>
                                            <a href="#"
                                               data-href="<?php echo $this->url('adminaut/module/delete', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $entity->getId()]); ?>"
                                               class="btn btn-danger btn-modal-delete delete"
                                               data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Delete', 'adminaut') ?>"
                                               data-original-title="<?php echo $this->translate('Delete', 'adminaut') ?>"><i class="fa fa-trash"></i></a>
                                        <?php } ?>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <script>
                        (function ($) {
                            $('#moduleEntityTable').DataTable({
                                "paging": true,
                                "lengthChange": true,
                                "searching": true,
                                "ordering": true,
                                "info": true,
                                "autoWidth": false,
                                "pageLength": Cookies.get('<?php echo $this->moduleOption->getModuleId(); ?>.dt.length') || 10
                            }).on('length.dt', function (e, settings, len) {
                                Cookies.set('<?php echo $this->moduleOption->getModuleId(); ?>.dt.length', len);
                            });
                        })(jQuery);
                    </script>
                </div>
                <!-- /.box-body -->

                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'add']); ?>"
                           class="btn btn-primary pull-left"><i class="fa fa-plus"></i> <?php echo $this->moduleOption->getLabels()['add_record'] ?></a>
                    <?php } ?>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::FULL)) { ?>
    <?php echo $this->partial('adminaut/partial/deleteModal'); ?>
<?php } ?>
