<?php
    $datatableColumns = $this->datatableColumns;
    $datatableOrders = [];

    foreach ($datatableColumns as $i => &$column) {
        if(isset($column['order']) && $column['order']) {
            $datatableOrders[] = [$i, $column['order']];
            unset($column['order']);
        }
    }
?>

<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($this->moduleOption->getModuleName()) ?>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', [
        'pages' => [
            ['title' => $this->moduleOption->getModuleName()],
        ],
    ]) ?>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'add']); ?>"
                           class="btn btn-primary pull-left"><i class="fa fa-plus"></i> <?php echo $this->translate($this->moduleOption->getLabels()['add_record'], 'adminaut') ?></a>
                    <?php } ?>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->partial('adminaut/partial/messages') ?>

                    <table id="moduleEntityTable" class="table table-striped table-bordered table-hover dataTables">
                        <thead>
                        <tr>
                            <th>#</th>
                            <?php foreach ($this->listedElements as $listedElement) { ?>
                                <?php if ($listedElement->getName() === 'id') { continue; } ?>
                                <th><?php echo $listedElement->getOption('label') ?></th>
                            <?php } ?>
                            <th><?php echo $this->translate('Actions', 'adminaut'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <script>
                        (function ($) {
                            $('#moduleEntityTable').adminautDataTable({
                                pageLength : parseInt(Cookies.get('<?php echo $this->moduleOption->getModuleId(); ?>.dt.length')) || 10,
                                ajax : {
                                    url : "<?php echo $this->url('adminaut/api/module/datatable', ['module_id' => $this->moduleOption->getModuleId()]) ?>"
                                },
                                columns : <?php echo json_encode($datatableColumns) ?>,
                                order : <?php echo json_encode($datatableOrders) ?>
                            }).on('length.dt', function (e, settings, len) {
                                Cookies.set('<?php echo $this->moduleOption->getModuleId(); ?>.dt.length', len);
                            });
                        })(jQuery);
                    </script>
                </div>
                <!-- /.box-body -->

                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'mode' => 'add']); ?>"
                           class="btn btn-primary pull-left"><i class="fa fa-plus"></i> <?php echo $this->translate($this->moduleOption->getLabels()['add_record'], 'adminaut') ?></a>
                    <?php } ?>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::FULL)) { ?>
    <?php echo $this->partial('adminaut/partial/deleteModal'); ?>
<?php } ?>
