<?php
$pages = [
    [
        'title' => $this->moduleOption->getModuleName(),
        'url' => $this->url('adminaut/module/list', [
            'module_id' => $this->moduleOption->getModuleId(),
        ]),
    ],
    [
        'title' => $this->escapeHtml($this->moduleOption->getLabels()['record_detail']),
    ],
];

$actions = [];
if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::WRITE)) {
    $actions[] = [
        'url' => $this->url('adminaut/module/action', [
            'module_id' => $this->moduleOption->getModuleId(),
            'entity_id' => $this->entity->getId(),
            'mode' => 'update',
        ]),
        'icon' => 'fa fa-pencil',
    ];
    $actions[] = [
        'url' => $this->url('adminaut/module/action', [
            'module_id' => $this->moduleOption->getModuleId(),
            'mode' => 'add',
        ]),
        'icon' => 'fa fa-plus',
    ];
}
?>
<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($this->moduleOption->getModuleName()) ?>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', ['pages' => $pages]) ?>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <?php echo $this->partial('adminaut/partial/tabs', [
            'url_params' => $this->url_params,
            'tabs' => $this->tabs,
            'actions' => $actions,
        ]) ?>
        <div class="tab-content">
            <?php echo $this->content ?>
        </div>
    </div>
</section>
