<?php
/** @var array $elements */
/** @var array $ignoreFields */
/** @var string $primary */
/** @var \Adminaut\Entity\Base $ignoredFields */
$ignoredFields = [];
$primaryFieldValue = isset($elements[$primary]) ? (method_exists($elements[$primary], 'getListedValue') ? $elements[$primary]->getListedValue() : $elements[$primary]->getValue()) : $entity->getId();

$pages = [
    [
        'title' => $this->moduleOption->getModuleName(),
        'url' => $this->url('adminaut/module/list', [
            'module_id' => $this->moduleOption->getModuleId(),
        ]),
    ],
    [
        'title' => $primaryFieldValue,
    ],
];

?>
<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($this->moduleOption->getModuleName()) ?>
        <small><?php echo $this->escapeHtml($primaryFieldValue) ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs', ['pages' => $pages]) ?>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12<?php echo sizeof($this->widgets) > 0 ? ' col-md-8' : '' ?>">
            <div class="nav-tabs-custom">
                <?php if (sizeof($this->tabs) > 1) { ?>
                    <?php echo $this->partial('adminaut/partial/tabs', [
                        'route' => 'adminaut/module/action',
                        'url_params' => $this->url_params,
                        'tabs' => $this->tabs,
                    ]) ?>
                <?php } else { ?>
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate('Detail', 'adminaut') ?></h3>
                    </div>
                <?php } ?>
                <div class="tab-content">
                    <?php echo $this->partial('adminaut/partial/messages') ?>
                    <fieldset class="form-horizontal">
                        <?php foreach ($elements as $fieldName => $field) { ?>
                            <?php
                            if (in_array($fieldName, $ignoredFields)) {
                                continue;
                            }

                            if ($field instanceof \Adminaut\Datatype\GoogleMap) {
                                if ($field->getLongitudeVariable()) {
                                    if (isset($elements[$field->getLongitudeVariable()])) {
                                        $field->setConnectedElement($elements[$field->getLongitudeVariable()]);
                                        $ignoredFields[] = $field->getLongitudeVariable();
                                    }
                                }
                            } else if ($field instanceof \Adminaut\Datatype\Location) {
                                if ($field->getLongitudeProperty()) {
                                    if (isset($elements[$field->getLongitudeProperty()])) {
                                        $field->setLongitudeElement($elements[$field->getLongitudeProperty()]);
                                        $ignoredFields[] = $field->getLongitudeProperty();
                                    }
                                }
                            }
                            ?>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><?php echo $field->getLabel() ?></label>
                                <div class="col-sm-10 view-value">
                                    <?php echo $this->datatypeDetail($field) ?>
                                </div>
                            </div>
                        <?php } ?>
                    </fieldset>
                </div>
                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleId(), 2)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', [
                            'module_id' => $this->moduleOption->getModuleId(),
                            'entity_id' => $this->entity->getId(),
                            'mode' => 'edit',
                        ]) ?>" class="btn btn-primary">
                            <?php echo $this->translate('Edit', 'adminaut') ?>
                        </a>
                    <?php } ?>
                    <a href="<?php echo $this->url('adminaut/module/list', ['module_id' => $this->moduleOption->getModuleId()]) ?>" class="btn btn-link">
                        <?php echo $this->translate('Back to list', 'adminaut') ?>
                    </a>
                    <div class="pull-right">
                        <a href="<?php echo $this->url('adminaut/module/action', [
                            'module_id' => $this->moduleOption->getModuleId(),
                            'entity_id' => $this->entity->getId(),
                            'mode' => 'add',
                        ]) ?>" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Copy', 'adminaut') ?>" data-original-title="Copy">
                            <i class="fa fa-clone"></i>
                        </a>
                        <a href="#" data-href="<?php echo $this->url('adminaut/module/delete', [
                            'module_id' => $this->moduleOption->getModuleId(),
                            'entity_id' => $this->entity->getId(),
                        ]) ?>" class="btn btn-sm btn-danger btn-modal-delete" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('Delete', 'adminaut') ?>" data-original-title="Delete">
                            <i class="fa fa-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-4">
            <?php foreach ($this->widgets as $widget) { ?>
                <?php echo $this->widget($widget); ?>
            <?php } ?>
        </div>
    </div>
</section>

<?php if ($this->isAllowed($this->moduleOption->getModuleId(), \Adminaut\Service\AccessControlService::FULL)) { ?>
    <?php echo $this->partial('adminaut/partial/deleteModal') ?>
<?php } ?>
