<section class="content-header">
    <h1>
        <?php echo $this->moduleOption->getModuleName() ?> <small><?php echo $this->entity->{'get'.ucfirst($this->primary)}(); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut/dashboard') ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate("Dashboard"); ?></a></li>
        <li><a href="<?php echo $this->url('adminaut/module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>"><?php echo $this->moduleOption->getModuleName() ?></a></li>
        <li class="active"><?php echo $this->entity->{'get'.ucfirst($this->primary)}() ?></li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <div class="nav-tabs-custom">
                <?php if(sizeof($this->tabs) > 1) { ?>
                    <?php echo $this->partial('partial/tabs.phtml', ['route' => 'adminaut/module/action', 'url_params' => $this->url_params, 'tabs' => $this->tabs]); ?>
                <?php } else { ?>
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate("Detail"); ?></h3>
                    </div>
                <?php } ?>
                <div class="tab-content">
                    <fieldset class="form-horizontal">
                    <?php foreach ($this->elements as $element) { ?>
                        <div class="form-group">
                            <?php $element->setValue($this->entity->{$element->getName()}); ?>
                            <label class="col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-sm-10 view-value">
                            <?php if(method_exists($element, 'getListedValue')) { ?>
                                <?php echo $element->getListedValue(); ?>
                            <?php } else { ?>
                                <?php echo $element->getValue(); ?>
                            <?php } ?>
                            </div>
                        </div>
                    <?php } ?>
                    </fieldset>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleName(), 2)) { ?>
                        <a href="<?php echo $this->url('adminaut/module/action', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $this->entity->getId(), 'mode' => 'edit']); ?>" class="btn btn-primary"><?php echo $this->translate('Edit'); ?></a>
                    <?php } ?>
                    <a href="<?php echo $this->url('adminaut/module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>" class="btn btn-link"><?php echo $this->translate('Back to list'); ?></a>
                    <a href="<?php echo $this->url('adminaut/module/delete', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $this->entity->getId()]); ?>" class="btn btn-danger pull-right"><?php echo $this->translate('Delete'); ?></a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>

        <div class="col-xs-12 col-sm-4">
            <div class="box">
                <div class="box-header with-border">
                    <i class="fa fa-fw fa-facebook"></i>
                    <h3 class="box-title">Facebook</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="fb-page" data-href="https://www.facebook.com/restaurace.dvorce" data-tabs="timeline, messages, events" data-small-header="false" data-width="1000" data-hide-cover="false" data-show-facepile="true" style="width: 100%;"><blockquote cite="https://www.facebook.com/restaurace.dvorce" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/restaurace.dvorce">Pivovarská restaurace Dvorce</a></blockquote></div>
                </div>
            </div>
        </div>
    </div>
</section>