<section class="content-header">
    <h1>
        <?php echo $this->moduleOption->getModuleName() ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('adminaut-dashboard') ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="<?php echo $this->url('adminaut-module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>"><?php echo $this->moduleOption->getModuleName() ?></a></li>
        <li class="active"><?php echo $this->moduleOption->getLabels()['entity_detail'] ?></li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="nav-tabs-custom">
                <?php if(sizeof($this->tabs) > 1) { ?>
                    <?php echo $this->partial('partial/tabs.phtml', ['url_params' => $this->url_params, 'tabs' => $this->tabs]); ?>
                <?php } else { ?>
                    <div class="box-header with-border">
                        <h3 class="box-title">Detail</h3>
                    </div>
                <?php } ?>
                <div class="tab-content">
                    <fieldset class="form-horizontal">
                    <?php foreach ($this->elements as $element) { ?>
                        <div class="form-group">
                            <?php $element->setValue($this->entity->{$element->getName()}); ?>
                            <label class="col-sm-1 control-label"><?php echo $element->getLabel() ?></label>
                            <div class="col-sm-10 view-value">
                            <?php if(method_exists($element, 'getListedValue')) { ?>
                                <?php echo $element->getListedValue(); ?>
                            <?php } else { ?>
                                <?php echo $element->getValue(); ?>
                            <?php } ?>
                            </div>
                        </div>
                    <?php } ?>
                    </fieldset>
                </div>
                <!-- /.tab-content -->
                <div class="box-footer clearfix">
                    <?php if ($this->isAllowed($this->moduleOption->getModuleName(), 2)) { ?>
                        <a href="<?php echo $this->url('adminaut-module/action', ['module_id' => $this->moduleOption->getModuleId(), 'entity_id' => $this->entity->getId(), 'mode' => 'edit']); ?>" class="btn btn-primary"><?php echo $this->translate('Edit'); ?></a>
                    <?php } ?>
                    <a href="<?php echo $this->url('adminaut-module/list', ['module_id' => $this->moduleOption->getModuleId()]); ?>" class="btn btn-link"><?php echo $this->translate('Back to list'); ?></a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
    </div>
</section>