<section class="content-header">
    <h1>
        <?php echo $this->translate('Module cyclic tab', 'adminaut') ?>
        <small><?php echo $this->translate('Edit', 'adminaut') ?></small>
    </h1>
    <?php echo $this->partial('adminaut/partial/breadcrumbs') ?>
</section>

<section class="content">
    <?php echo $this->partial('adminaut/partial/messages') ?>

    <?php // todo: Create some content. ?>
</section>
