<div class="login-box">
    <div class="login-logo">
        <a href="<?php echo $this->url('adminaut/user/login') ?>">Adminaut</a>
    </div>
    <!-- /.login-logo -->
    <div class="box login-box-body box-success">
        <p class="login-box-msg"><?php echo $this->translate("Forgot password"); ?></p>

        <form action="#" method="post">
            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" name="submit" class="btn btn-primary btn-flat pull-right" value="">Send new password</button>
                    <a href="<?php echo $this->url('adminaut/user/login') ?>" class="btn btn-default btn-flat pull-right" value="">Back</a>
                </div>
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->