<div class="row">
<div class="col-lg-12">
    <h1 class="page-header"><?php echo $this->translate('Install - Add new user'); ?></h1>
</div>
</div>

<div class="row">
    <div class="col-lg-9">

        <?php echo $this->partial('partial/flashMessanger.phtml', ['flashMessenger' => $this->flashMessenger()]); ?>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('adminaut-install'));
        $form->prepare();
        echo $this->form(null, null)->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>

    </div>
</div>