<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('adminaut-install'));
    $form->prepare();
?>
<div class="login-box">
    <?php echo $this->form(null, null)->openTag($form); ?>
    <div class="login-logo">
        <a href="<?php echo $this->url('adminaut-user/login') ?>">Adminaut</a>
    </div>
    <!-- /.login-logo -->
    <div class="box login-box-body box-success">
        <p class="login-box-msg"><?php echo $this->translate("Register first user"); ?></p>

        <?php echo $this->partial('partial/flashMessanger.phtml', ['flashMessenger' => $this->flashMessenger()]); ?>
        <?php
            echo $this->formCollection($form);
        ?>

    </div>
    <!-- /.login-box-body -->
    <?php echo $this->form()->closeTag(); ?>
</div>
<!-- /.login-box -->