<?php

/** @var \Zend\Form\Form $form */
$form = $this->form;

$form->setAttribute('action', $this->url(\Adminaut\Controller\InstallController::ROUTE_INDEX));
$form->prepare();
?>
<div class="login-box">
    <?php echo $this->form(null, null)->openTag($form) ?>
    <div class="box login-box-body">
        <?php echo $this->partial('adminaut/partial/messages') ?>
        <p class="login-box-msg">
            <?php echo $this->translate('Register first user') ?>
        </p>
        <?php echo $this->formCollection($form) ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>
