<?php

/** @var \Adminaut\Form\PasswordRecoveryStepOneForm $form */


$this->headTitle($this->translate('Forgotten password', 'adminaut'));
$form->prepare();
?>

<div class="login-box">
    <div class="login-box-body">
        <?php echo $this->partial('adminaut/partial/messages') ?>

        <p class="login-box-msg"><?php echo $this->translate('Enter your email', 'adminaut') ?></p>

        <?php echo $this->form()->openTag($form) ?>

        <div class="form-group<?php if (sizeof($form->get('email')->getMessages()) > 0) { echo ' has-error'; } ?>">
            <?= $this->formElement($form->get('email')) ?>
            <?= $this->formElementErrors($form->get('email')) ?>
        </div>

        <div class="clearfix">
            <div class="pull-left">
                <a href="<?php echo $this->url(\Adminaut\Controller\AuthController::ROUTE_LOGIN) ?>">
                    <?php echo $this->translate('Back', 'adminaut') ?>
                </a>
            </div>
            <div class="pull-right">
                <button type="submit" class="btn btn-primary btn-block btn-flat">
                    <?php echo $this->translate('Recover password', 'adminaut') ?>
                </button>
            </div>
        </div>

        <?php echo $this->form()->closeTag() ?>

    </div>
</div>

