<?php

/** @var \Adminaut\Form\UserLoginForm $form */
$form = $this->form;

if (isset($this->redirect) && null !== $this->redirect) {
    $url = $this->url(\Adminaut\Controller\AuthController::ROUTE_LOGIN, [], ['query' => ['redirect' => $this->redirect]]);
} else {
    $url = $this->url(\Adminaut\Controller\AuthController::ROUTE_LOGIN);
}

$form->setAttribute('action', $url);
$form->prepare();
?>
<div class="login-box">
    <?php echo $this->form(null, null)->openTag($form) ?>
    <div class="box login-box-body">
        <?php echo $this->partial('adminaut/partial/messages') ?>
        <p class="login-box-msg">
            <?php echo $this->translate('Sign in to start your session', 'adminaut') ?>
        </p>
        <?php echo $this->formCollection($form) ?>
        <a href="<?php echo $this->url(\Adminaut\Controller\AuthController::ROUTE_FORGOTTEN_PASSWORD) ?>">
            <?php echo $this->translate('I forgot my password', 'adminaut') ?>
        </a>
        <?php /*<br>
        <a href="<?php echo $this->url(\Adminaut\Controller\AuthController::ROUTE_REQUEST_ACCESS) ?>">
            <?php echo $this->translate('Request access', 'adminaut') ?>
        </a>*/ ?>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>
