<?php

/** @var \Adminaut\Form\PasswordRecoveryStepTwoForm $form */
$form = $this->form;

$form->prepare();
?>
<div class="login-box">
    <?php echo $this->form(null, null)->openTag($form) ?>
    <div class="box login-box-body">
        <?php echo $this->partial('adminaut/partial/messages') ?>
        <p class="login-box-msg">
            <?php echo $this->translate('Set your new password', 'adminaut') ?>
        </p>
        <?php echo $this->formCollection($form) ?>

        <div class="clearfix">
            <div class="pull-left">
                <a href="<?php echo $this->url(\Adminaut\Controller\AuthController::ROUTE_LOGIN) ?>">
                    <?php echo $this->translate('Back', 'adminaut') ?>
                </a>
            </div>
            <div class="pull-right">
                <button type="submit" class="btn btn-primary btn-block btn-flat">
                    <i class="fa fa-check"></i>
                    <?php echo $this->translate('Set new password', 'adminaut') ?>
                </button>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
</div>
