<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php

    echo $this->headTitle($this->adminautAppearance('title'))->setSeparator(' | ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('robots', 'noindex, nofollow')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('adminaut/img/favicon.ico')])
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath('adminaut/themes/adminlte/dist/css/AdminLTE.min.css'))
        ->appendStylesheet($this->basePath('adminaut/themes/adminlte/dist/css/skins/skin-blue.min.css'));

    echo $this->headScript()
        ->appendFile($this->basePath('adminaut/js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ->appendFile($this->basePath('adminaut/js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ->appendFile('//code.jquery.com/jquery-1.11.1.min.js')
        ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
        ->appendFile($this->basePath('adminaut/themes/adminlte/dist/js/app.min.js'));

    ?>

</head>
<body class="hold-transition skin-green<?php echo ' ' . implode($this->bodyClasses) ?>">
<?php echo $this->content ?>
</body>
</html>
