<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Adminaut')->setSeparator(' | ')->setAutoEscape(false);

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('author', 'Massimo Filippi s.r.o. (www.mfcc.cz)');

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('img/adminaut/favicon.ico')))
            ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
            ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css')
            ->appendStylesheet($this->basePath('css/adminaut/timeline.css'))
            ->appendStylesheet('https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css')
            ->appendStylesheet($this->basePath('css/adminaut/bootstrap-datetimepicker.min.css'))
            ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')
            ->appendStylesheet($this->basePath('css/adminaut/dataTables.bootstrap.css'))
            ->appendStylesheet($this->basePath('css/adminaut/dataTables.responsive.css'))
            ->appendStylesheet($this->basePath('css/adminaut/morris.css'))
            ->appendStylesheet($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/css/AdminLTE.min.css'))
            ->appendStylesheet($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/css/skins/skin-green.min.css'));

        echo $this->headScript()
            ->appendFile($this->basePath('js/adminaut/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile($this->basePath('js/adminaut/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile('//code.jquery.com/jquery-1.11.1.min.js')
            ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
            ->appendFile('https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js')
            ->appendFile($this->basePath('js/adminaut/moment.min.js'))
            ->appendFile($this->basePath('js/adminaut/bootstrap-datetimepicker.min.js'))
            ->appendFile($this->basePath('js/adminaut/jquery.dataTables.min.js'))
            ->appendFile($this->basePath('js/adminaut/dataTables.bootstrap.min.js'))
            ->appendFile($this->basePath('js/adminaut/morris.min.js'))
            ->appendFile($this->basePath('js/adminaut/raphael-min.js'))
            ->appendFile($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/js/app.min.js'));

        ?>

    </head>
    <body class="hold-transition skin-green sidebar-mini">
        <header class="main-header">
            <!-- Logo -->
            <a href="<?php echo $this->url('adminaut'); ?>" class="logo">
                <span class="logo-lg">Adminaut</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="<?php echo $this->basePath("/adminaut/themes/almasaeed2010/adminlte/dist/img/user2-160x160.jpg"); ?>" class="user-image" alt="<?php echo $this->userIdentity()->getName(); ?>">
                                <span class="hidden-xs"><?php echo $this->userIdentity()->getName(); ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="<?php echo $this->basePath("/adminaut/themes/almasaeed2010/adminlte/dist/img/user2-160x160.jpg"); ?>" class="img-circle" alt="<?php echo $this->userIdentity()->getName(); ?>">

                                    <p>
                                        <?php echo $this->userIdentity()->getName(); ?>
<!--                                        <small>Member since Nov. 2012</small>-->
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="<?php echo $this->url('adminaut-users/show', ['id' => $this->userIdentity()->getId()]); ?>" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('adminaut-user/logout'); ?>" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="<?php echo $this->basePath("/adminaut/themes/almasaeed2010/adminlte/dist/img/user2-160x160.jpg"); ?>" class="img-circle" alt="<?php echo $this->userIdentity()->getName(); ?>">
                    </div>
                    <div class="pull-left info">
                        <p><?php echo $this->userIdentity()->getName(); ?></p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?php
                echo $this->navigation(\Adminaut\Navigation\Navigation::class)->menu()
                    ->setUlClass('nav')
                    ->setPartial('partial/navigation/navigation.phtml');
                ?>
            </section>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            <?php
            // TODO
            //echo $this->navigation('Navigation')->breadcrumbs()->setPartial(false); ?>

            <?php echo $this->content; ?>
        </div>

        <footer class="main-footer">
            Powered by <a href="http://adminaut.com/" target="_blank">Adminaut</a>
        </footer>

        <?php echo $this->inlineScript(); ?>

    </body>
</html>