<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Adminaut')->setSeparator(' | ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('author', 'Massimo Filippi s.r.o. (www.mfcc.cz)');

    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('img/adminaut/favicon.ico')))
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css')
        ->appendStylesheet($this->basePath('css/adminaut/timeline.css'))
        ->appendStylesheet('https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css')
        ->appendStylesheet($this->basePath('css/adminaut/bootstrap-datetimepicker.min.css'))
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath('css/adminaut/dataTables.bootstrap.css'))
        ->appendStylesheet($this->basePath('css/adminaut/dataTables.responsive.css'))
        ->appendStylesheet($this->basePath('css/adminaut/morris.css'))
        ->appendStylesheet($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/css/AdminLTE.min.css'))
        ->appendStylesheet($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/css/skins/skin-green.min.css'));

    echo $this->headScript()
        ->appendFile($this->basePath('js/adminaut/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ->appendFile($this->basePath('js/adminaut/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ->appendFile('//code.jquery.com/jquery-1.11.1.min.js')
        ->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
        ->appendFile('https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js')
        ->appendFile($this->basePath('js/adminaut/moment.min.js'))
        ->appendFile($this->basePath('js/adminaut/bootstrap-datetimepicker.min.js'))
        ->appendFile($this->basePath('js/adminaut/jquery.dataTables.min.js'))
        ->appendFile($this->basePath('js/adminaut/dataTables.bootstrap.min.js'))
        ->appendFile($this->basePath('js/adminaut/morris.min.js'))
        ->appendFile($this->basePath('js/adminaut/raphael-min.js'))
        ->appendFile($this->basePath('adminaut/themes/almasaeed2010/adminlte/dist/js/app.min.js'));

    ?>

</head>
<body class="hold-transition skin-green<?php echo " ".implode($this->bodyClasses) ?>">

<?php echo $content ?>

<?php echo $this->inlineScript(); ?>

</body>
</html>