<div class="login-box">

    <div class="login-logo">
        <a href="<?php echo $this->url('adminaut/user/login') ?>">Adminaut</a>
    </div>

    <div class="box login-box-body">

        <?php echo $this->partial('partial/messages.phtml'); ?>

        <p class="login-box-msg"><?php echo $this->translate("Sign in to start your session"); ?></p>

        <?php

        /** @var Adminaut\Form\UserLogin $form */
        $form = $this->form;

        if ($this->redirect) {
            $url = $this->url('adminaut/user/login', [], ['query' => ['redirect' => $this->redirect]]);
        } else {
            $url = $this->url('adminaut/user/login');
        }
        $form->setAttribute('action', $url);
        $form->prepare();

        echo $this->form(null, null)->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>

        <a href="<?php echo $this->url('adminaut/user/forgot-password'); ?>"><?php echo $this->translate("I forgot my password"); ?></a><br>
        <a href="#"><?php echo $this->translate("Request access"); ?></a>

    </div>

</div>
